### ISSUE TITLE
Plotting windows in grouped lagged dataframe

### ISSUE THREAD

**Issue by edgBR** [nredell/forecastML#24]
Dear nredell,

First of all congratulations for your package. So far for me the highlight of 2019 in time series forecasting without any doubt.

I have a dataframe that I am grouping as follows:

```
data_train_list <- forecastML::create_lagged_df(data %>% select(-c("snsr_dt")),
                                           type = "train",
                                           outcome_col = 1,
                                           lookback = 1:18,
                                           horizons = c(1, 6, 12, 15, 18),
                                           dates = as.Date(data$snsr_dt),
                                           dynamic_features = c("dayW", "dayM", "dayY", "month", "quarter", "year", "weekN"),
                                           groups = c("system", "signal_tag"),
                                           frequency = "1 day")

p <- plot(data_train_list)  # plot.lagged_df() returns a ggplot object.
p <- p + geom_tile(NULL)  # Remove the gray border for a cleaner plot.
p

windows <- forecastML::create_windows(data_train_list, window_length = 15, skip = 0,
                                      include_partial_window = TRUE)
```

I was trying to plot the windows according to:

```
p <- plot(windows, data_train_list, group_filter="system == X & signal_tag == Y) + 
            theme(legend.position = "none")
p

```

The plot is "working" but I get the following error:

```
Warning message:
In drawGTree(x) : reached elapsed time limit
> p
Warning messages:
1: Removed 462 rows containing missing values (geom_path). 
2: Removed 460 rows containing missing values (geom_point). 
> 
```

Also I show in the plot the number of windows that are applicable for all the groups have as a result the following:

https://ibb.co/sKPXyB6

**Comment by nredell** [comment]
Thanks for the nice words, there's a lot of functionality/robustness that I plan to add going forward. And v0.8.0 just hit CRAN on Friday with a bunch of updates. I'd give that version a spin, although I don't believe that it will help here.

I've seen similar errors in my R life and they appear to come from RStudio itself. My guess is that's it's a memory issue. I see 200 windows, and if you have many groups, RStudio is probably giving up. There may be a global `options()` that you can adjust in your R session.

On a related note, I see that you have multiple groups. Of all the testing that I've done, I haven't spent much time on multiple groups.....aaand I just broke the pipeline with a multiple groups example.

I'll see if I can't fix this quickly. The quick approach to get your problem working would be to paste/concatenate your two groups into a single grouping column and go from there.

**Comment by nredell** [comment]
Fixed
