### ISSUE TITLE
Rolling Features 

### ISSUE THREAD

**Issue by Akai01** [nredell/forecastML#29]
Dear Nick,

Is it possible to add rolling features such as rolling mean of the label or of the lag variables?

Best Regards

Res

**Comment by nredell** [comment]
At present, no. The rationale behind no moving averages was that they would definitely leak data/info into the held out validation datasets.

Additional cross-validation schemes that would work with rolling features is on my to-do list for v1.0.0.

**Comment by Akai01** [comment]
@nredell thank you for your quick reply. 

Br

Res
