### ISSUE TITLE
Error plotting data_error

### ISSUE THREAD

**Issue by sarasusan** [nredell/forecastML#33]
Hello I am a student and I am trying to apply this software to a case study. I am getting some errors when trying to replicate your article (https://cran.r-project.org/web/packages/forecastML/vignettes/package_overview.html). Can you help me?

`> plot(data_error, facet = ~ horizon, type = "window")
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'`

`> plot(data_error, facet = ~ horizon, type = "global")
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'`

`> plot(data_error, type = "horizon", facet = ~ horizon)
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'`

**Comment by nredell** [comment]
Do you have `packageVersion("forecastML")` >= .0.9.0 installed?

I made a breaking change from v0.8.0 to v0.9.0 where the error plots don't take the training datasets as the second argument...just the error datasets like in the example above...which wouldn't work with v0.8.0.

I just ran the vignette and it worked on my machine.

**Comment by sarasusan** [comment]
I upgraded from 0.8.0 to 0.9.0 and it worked. Thank you

**Comment by nredell** [comment]
Good deal. These annoying little changes should stop when v1.0.0 is released.

Thanks for opening the issue and good luck on the case study.
