### ISSUE TITLE
Just a small doubt...

### ISSUE THREAD

**Issue by coforfe** [nredell/forecastML#37]
Hello Nickalus,

Firstly, thanks a lot for your package which is opening new ways to treat TimeSeries.

Perhaps it is not the purpose of your package, but I was unable to find an example based on an univariate time series. 

Well, perhaps there is a way to apply some of the approaches that your package has for this kind of time series, with the intermediation of another package like `[timetk](https://cran.r-project.org/web/packages/timetk/index.html)`.

Any advice will be very welcome.

Thanks in advance,
Carlos.

**Comment by nredell** [comment]
Thanks for the kind words.

The purpose of this package is flexibility in forecasting so it's whatever people use it for :)

Below is a simple example with a univariate time series and `lm()`...just a simple autoregressive model. It's a bit more code than a statistical forecast in `forecast` or `fable`, and ARIMA or ETS will perform better here anyhow.
```
library(forecast)
library(forecastML)

data(wineind, package = "forecast")

data <- data.frame("outcome" = unclass(wineind))

frequency <- "1 month"

dates <- seq(as.Date("1980-01-01"), as.Date("1994-08-01"), by = frequency)

data_train <- forecastML::create_lagged_df(data, type = "train", method = "direct",
                                           outcome_col = 1, lookback = 1:12, 
                                           horizons = 1:12, dates = dates, frequency = frequency)

windows <- forecastML::create_windows(data_train, window_length = 0)

model_fun <- function(data) {
  model <- lm(outcome ~ ., data)
}

model_results <- forecastML::train_model(data_train, windows, model_name = "OLS", model_function = model_fun)

prediction_fun <- function(model, data) {
  data_pred <- as.data.frame(predict(model, data, interval = "prediction"))
}

data_forecast <- forecastML::create_lagged_df(data, type = "forecast", method = "direct",
                                              outcome_col = 1, lookback = 1:12, 
                                              horizons = 1:12, dates = dates, frequency = frequency)

data_forecasts <- predict(model_results, prediction_function = list(prediction_fun), data = data_forecast)

data_forecasts <- forecastML::combine_forecasts(data_forecasts)

plot(data_forecasts, data[dates >= as.Date("1992-01-01"), , drop = FALSE], 
     dates[dates >= as.Date("1992-01-01")]) + theme(legend.position = NULL)
```

**Comment by nredell** [comment]
As for `timetk`, there is an example at the end of this issue: [https://github.com/nredell/forecastML/issues/30](https://github.com/nredell/forecastML/issues/30).

I'm always looking for ways to make things effortless so I'll think more about the univariate case with only date-based features.

**Comment by coforfe** [comment]
Thanks for both things!.
