### ISSUE TITLE
reconcile_forecasts not found in forecastML

### ISSUE THREAD

**Issue by satya-pattnaik** [nredell/forecastML#43]
I am using version 0.9.0, and the reconcile_forecasts is not a valid function. How to get access to v0.9.1 CRAN?

**Comment by nredell** [comment]
I'm not sure when I'll be able to get around to another CRAN release, but you can install the dev version with `remotes::install_github("nredell/forecastML")` to get this function.

The temporal hierarchical reconciliation should be solid, but I would consider the cross-sectional or grouped reconciliation experimental if I even left it in there.

On that note, the recently released `FoReco` package looks slick and is more fully featured than `reconcile_forecasts()`. I haven't used it, but the paper they put out is legit. A generic, dedicated reconciliation package like this is long overdue. I was sitting on the package name `reconcileR` for just this but alas someone beat me to it.

https://github.com/daniGiro/FoReco

**Comment by satya-pattnaik** [comment]
Thanks @nredell . The FoReco package seems to be really promising. I was searching for a MIT licensed package though, so that I can incorporate it into my products. Anyways will find a workaround. Thanks for the info!
